# -*- coding: utf-8 -*-
"""Chap2Ex2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PflT08DFm5qDRKFHGymDclI-kzHZeEQ
"""

f_person = "Nelson Mandela"
quote = ("\"It always seems impossible until it\'s done.\"")
print(f_person + " once said, " + quote)
