# -*- coding: utf-8 -*-
"""Chap2Ex4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PflT08DFm5qDRKFHGymDclI-kzHZeEQ
"""

fave_number = "25"
message = ("My favorite number is " + fave_number)
print(message)
