# -*- coding: utf-8 -*-
"""Chap2Ex3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PflT08DFm5qDRKFHGymDclI-kzHZeEQ
"""

name = "\tRailey Anthony Maala Inductivo\n"
print(name)
print(name.lstrip())
print(name.rstrip())
print(name.strip())