# -*- coding: utf-8 -*-
"""Chap2Ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PflT08DFm5qDRKFHGymDclI-kzHZeEQ
"""

var1 = ("that message")
var1 = ("that other message")
print(var1)